# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

- task: S3Upload@1
  inputs:
    awsCredentials: 'aws'
    regionName: '$(REGION)'
    bucketName: '$(BUCKET_NAME)'
    sourceFolder: '/'
    globExpressions: '!*.yml'
