# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - task: S3Upload@1
    inputs:
      awsCredentials: 'aws'
      regionName: '$(REGION)'
      bucketName: '$(BUCKET_NAME)'
      sourceFolder: '$(Pipeline.Workspace)'
      globExpressions: |
        **
        !*.yml
        !.git/**

  - task: AWSCLI@1
    inputs:
      awsCredentials: 'aws'
      regionName: '$(REGION)'
      awsCommand: 'cloudfront'
      awsSubCommand: 'create-invalidation'
      awsArguments: '--distribution-id $(DISTRIBUTION_ID) --paths /*'
